services:
  complaints-api:
    container_name: complaints-api
    image: docker.io/artmkrvshn/complaints-api
    environment:
      spring.datasource.url: jdbc:postgresql://postgres:5432/complaints
      spring.docker.compose.enabled: false
    ports:
      - 8080:8080
    networks:
      - complaints-api-network
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: 'postgres:16.3'
    environment:
      POSTGRES_DB: complaints
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - 5433:5432
    networks:
      - complaints-api-network
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 0.5s
      retries: 10

volumes:
  postgres:

networks:
  complaints-api-network: