CREATE TABLE customers
(
    id       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name     VARCHAR NOT NULL,
    email    VARCHAR NOT NULL,
    password VARCHAR NOT NULL,
    UNIQUE (email)
);

INSERT INTO customers (name, email, password)
VALUES ('John Doe', 'john.doe@email.com', 'john.doe'),
       ('Admin', 'admin@gmail.com', 'admin'),
       ('User 1', 'user1@gmail.com', 'user1'),
       ('User 2', 'user2@gmail.com', 'user2'),
       ('User 3', 'user3@gmail.com', 'user3');